---

- hosts: web
  
  vars:
   root_password: 'root'

  tasks:
  - name: installation Mariadb
    dnf:
     name: "{{ item }}"
     state: present
    loop:
     - mariadb
     - python3-PyMySQL
     - mariadb-server
  - name:  Activation Mariadb
    systemd:
     name: mariadb
     state: started
     enabled: yes
  - name: ajout .my.cnf conf mariadb
    copy:
     src: .my.cnf
     dest: /root/.my.cnf
  - name: Ajout du user mariadb 'clem' avec  password 'root'  et tout privileges
    mysql_user:
     name: clem
     password: root
     priv: '*.*:ALL'
     state: present
